### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [NZLWally/prj-rev-bwfs-dasmoto#4]
Your project was well structured and organized due to your consistency with indentations and whitespace. With minor fixes in the choice of selectors, your code would be perfect!

++ Consistency with indentations and whitespace.
++ Relative paths over absolute. Organized file tree.
++ All necessary styling attributes present.

-- Usage of IDs over classes.

Overall, superb job! Keep it up!

Grade: Meets expectation.

**Comment by NZLWally** [comment]
Thanks Joseph, really useful feedback.

I understand your comments around the specificity of classes versus ids. I will add comments in future to aid readability too.

Thanks,

James

________________________________
